// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypoeeaddaihoppgizdix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwb2VlYWRkYWlob3BwZ2l6ZGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTMxMjMsImV4cCI6MjA3MjMyOTEyM30.PYTC--mEb8iRCTIOWna0MWTZDRecshMGZtf9baqzgOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});